# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import (QFileDialog, QApplication, QFileDialog, QBoxLayout,QWidget)
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QDir
from wulee_v1 import WuleeLastestVersion

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):    
        self.wulee=WuleeLastestVersion()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 755)
        MainWindow.setStyleSheet("background: rgb(214, 214, 214);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tieu_de = QtWidgets.QLabel(self.centralwidget)
        self.tieu_de.setGeometry(QtCore.QRect(-10, 0, 961, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.tieu_de.setFont(font)
        self.tieu_de.setStyleSheet("border:1px solid gray;\n"
"color:white;\n"
"background-color:gray;\n"
"\n"
"")
        self.tieu_de.setAlignment(QtCore.Qt.AlignCenter)
        self.tieu_de.setWordWrap(False)
        self.tieu_de.setObjectName("tieu_de")
        self._import = QtWidgets.QPushButton(self.centralwidget)
        self._import.setGeometry(QtCore.QRect(10, 80, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._import.setFont(font)
        self._import.setStyleSheet("border-radius:20px;\n"
"border:1px solid black;\n"
"color:white;\n"
"background-color:gray;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_icon/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._import.setIcon(icon)
        self._import.setIconSize(QtCore.QSize(30, 30))
        self._import.setObjectName("_import")
        self._image_path = QtWidgets.QLabel(self.centralwidget)
        self._image_path.setGeometry(QtCore.QRect(10, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._image_path.setFont(font)
        self._image_path.setStyleSheet("color:black;\n"
"")
        self._image_path.setAlignment(QtCore.Qt.AlignCenter)
        self._image_path.setObjectName("_image_path")
        self._hide = QtWidgets.QPushButton(self.centralwidget)
        self._hide.setGeometry(QtCore.QRect(250, 80, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._hide.setFont(font)
        self._hide.setStyleSheet("border-radius:20px;\n"
"border:1px solid black;\n"
"color:white;\n"
"background-color:gray;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_icon/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._hide.setIcon(icon1)
        self._hide.setIconSize(QtCore.QSize(30, 30))
        self._hide.setObjectName("_hide")
        self._retrieve = QtWidgets.QPushButton(self.centralwidget)
        self._retrieve.setGeometry(QtCore.QRect(490, 80, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._retrieve.setFont(font)
        self._retrieve.setStyleSheet("border-radius:20px;\n"
"border:1px solid black;\n"
"color:white;\n"
"background-color:gray;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_icon/extract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._retrieve.setIcon(icon2)
        self._retrieve.setIconSize(QtCore.QSize(30, 30))
        self._retrieve.setObjectName("_retrieve")
        self._save = QtWidgets.QPushButton(self.centralwidget)
        self._save.setGeometry(QtCore.QRect(730, 80, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._save.setFont(font)
        self._save.setStyleSheet("border-radius:20px;\n"
"border:1px solid black;\n"
"color:white;\n"
"background-color:gray;\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._save.setIcon(icon3)
        self._save.setIconSize(QtCore.QSize(30, 30))
        self._save.setObjectName("_save")
        self._viewPath = QtWidgets.QLabel(self.centralwidget)
        self._viewPath.setGeometry(QtCore.QRect(10, 170, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self._viewPath.setFont(font)
        self._viewPath.setStyleSheet("color:black;\n"
"border:2px solid gray;\n"
"background-color:white;\n"
"")
        self._viewPath.setAlignment(QtCore.Qt.AlignCenter)
        self._viewPath.setObjectName("_viewPath")
        self._viewImage = QtWidgets.QLabel(self.centralwidget)
        self._viewImage.setGeometry(QtCore.QRect(10, 210, 431, 261))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self._viewImage.setFont(font)
        self._viewImage.setStyleSheet("color:black;\n"
"background-color:white;\n"
"border:2px solid gray;\n"
"")
        self._viewImage.setAlignment(QtCore.Qt.AlignCenter)
        self._viewImage.setObjectName("_viewImage")
        self._messages = QtWidgets.QLabel(self.centralwidget)
        self._messages.setGeometry(QtCore.QRect(490, 520, 441, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self._messages.setFont(font)
        self._messages.setStyleSheet("color:black;\n"
"border:2px solid gray;\n"
"background-color:white")
        self._messages.setText("")
        self._messages.setAlignment(QtCore.Qt.AlignCenter)
        self._messages.setObjectName("_messages")
        self._image_path_6 = QtWidgets.QLabel(self.centralwidget)
        self._image_path_6.setGeometry(QtCore.QRect(490, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._image_path_6.setFont(font)
        self._image_path_6.setStyleSheet("color:black;\n"
"")
        self._image_path_6.setAlignment(QtCore.Qt.AlignCenter)
        self._image_path_6.setObjectName("_image_path_6")
        self._image_path_7 = QtWidgets.QLabel(self.centralwidget)
        self._image_path_7.setGeometry(QtCore.QRect(490, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._image_path_7.setFont(font)
        self._image_path_7.setStyleSheet("color:black;")
        self._image_path_7.setAlignment(QtCore.Qt.AlignCenter)
        self._image_path_7.setObjectName("_image_path_7")
        self._notifications = QtWidgets.QTextEdit(self.centralwidget)
        self._notifications.setGeometry(QtCore.QRect(490, 170, 441, 301))
        self._notifications.setStyleSheet("color:black;\n"
"border:2px solid gray;\n"
"background-color:white")
        self._notifications.setObjectName("_notifications")
        self._password = QtWidgets.QLineEdit(self.centralwidget)
        self._password.setGeometry(QtCore.QRect(10, 520, 431, 31))
        self._password.setStyleSheet("color:black;\n"
"border:2px solid gray;\n"
"background-color:white")
        self._password.setEchoMode(QtWidgets.QLineEdit.Password)
        self._password.setObjectName("_password")
        self._image_path_8 = QtWidgets.QLabel(self.centralwidget)
        self._image_path_8.setGeometry(QtCore.QRect(10, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._image_path_8.setFont(font)
        self._image_path_8.setStyleSheet("color:black;")
        self._image_path_8.setAlignment(QtCore.Qt.AlignCenter)
        self._image_path_8.setObjectName("_image_path_8")
        self._setkey = QtWidgets.QPushButton(self.centralwidget)
        self._setkey.setGeometry(QtCore.QRect(310, 570, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self._setkey.setFont(font)
        self._setkey.setStyleSheet("\n"
"border:1px solid black;\n"
"color:white;\n"
"background-color:gray;\n"
"")
        self._setkey.setIconSize(QtCore.QSize(30, 30))
        self._setkey.setObjectName("_setkey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.set_event_connection()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tieu_de.setText(_translate("MainWindow", "WU - LEE STEGANOGRAPHY"))
        self._import.setText(_translate("MainWindow", "IMPORT"))
        self._image_path.setText(_translate("MainWindow", "IMAGE PATH"))
        self._hide.setText(_translate("MainWindow", "HIDE"))
        self._retrieve.setText(_translate("MainWindow", "RETRIEVE"))
        self._save.setText(_translate("MainWindow", "SAVE"))
        self._viewPath.setText(_translate("MainWindow", "IMAGE IS NULL"))
        self._viewImage.setText(_translate("MainWindow", "PREVIEW IMAGE"))
        self._image_path_6.setText(_translate("MainWindow", "NOTIFICATIONS"))
        self._image_path_7.setText(_translate("MainWindow", "MESSAGES"))
        self._image_path_8.setText(_translate("MainWindow", "PASSWORD"))
        self._setkey.setText(_translate("MainWindow", "SET KEY"))
        self._notifications.setReadOnly(True)
        # self._messages.setReadOnly(False)

    def set_event_connection(self):
        self._import.clicked.connect(self.getfile)
        self._hide.clicked.connect(self.testFunction)
        self._setkey.clicked.connect(self.set_key)

    def set_key(self):
        self.wulee.set_key(self._password.text())
        
    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle('Test')
        msg.setText('this is the text')
        x = msg.exec_()
    
    def getfile(self):
      file_name, _ = QFileDialog.getOpenFileName(QtWidgets.QMainWindow(), 'Open Image File',r"D:\\Picture\\","Image files (*.jpg *.jpeg *.gif *.png)")
      self._viewImage.setPixmap(QPixmap(file_name))
      self._viewPath.setText(file_name)
    
    def testFunction(self):
      self._viewPath.setText('abcd')
      self.wulee.text()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

